Algoritmo "Variáveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/09/2022
Var
// Seção de Declarações das variáveis 
     nota: inteiro, nota2: real, nome: caractere, passou: logico;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo